name: Flutter-App nach Web-App kompilieren
on:
  push:
jobs:
  build_webapp:
    runs-on: ubuntu-latest
    steps:
    - name: Repo auschecken
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'
        channel: 'stable'